aws-cloudformation/rain

cfn/format/common.go, cfn/format/common_test.go
=> Fix quoted strings as per #15

build.sh
*Issue #, if available:* #17
*Description of changes:* Add `nocgo` build variant
=> Add a variant without CGO to the build script as per #17

cfn/cfn_test.go, cfn/parse/parse.go, cfn/parse/parse_test.go, cfn/parse/test.yaml, cfn/parse/transform.go, cfn/spec/generate/main.go, examples/account-number.template, go.mod, go.sum
=> Rework parser

cmd/deploy.go
NA
* This PR adds additional information to the documentation for `rain deploy`.
I was unclear about the behavior of `deploy` when providing a template that needed to be packaged. This is the information I would have liked to have known.
=> Add detail to behaviour of deploy command

.pre-commit-hooks.yaml, internal/cmd/fmt/fmt.go, internal/cmd/wrap.go
*Description of changes:* Add pre-commit configuration for cfn-format
=> Pre commit

internal/cmd/rm/rm.go
*Issue #, if available: #50
*Description of changes: Use No as default value for removing stack
=> Use No as default value for removing stack

internal/aws/cfn/mock.go, internal/cmd/deploy/deploy.go, internal/cmd/deploy/deploy_test.go, internal/cmd/rm/rm.go, test/func_test.go
*Issue #, if available:* #37
*Description of changes:* Add -t flag on deploy for termination protection
=> Enhancement #37

internal/aws/cfn/cfn.go, internal/cmd/deploy/deploy.go, internal/cmd/deploy/util.go, internal/console/spinner/spinner.go
*Issue #, if available:* 45
*Description of changes:* Add support for showing nested changesets
=> Show nested changeset data during deploy #45

internal/aws/s3/mock.go, internal/aws/s3/s3.go
*Issue #, if available:* #49
*Description of changes:* BucketExists function distinguish between NotFound error and others.
=> fix: BucketExists function distinguish between NotFound and others.

README.md, cft/spec/internal/main.go, cft/spec/internal/sam.sh, docs/README.tmpl
Update CloudFormation specification file. Needed make some modification in order to generate it successfully. 
=> Update cfn specification file

.gitignore, cft/comments_test.go, cft/format/format.go, cft/format/format_test.go, internal/aws/aws.go, internal/cmd/fmt/fmt.go, test/templates/comments.yaml, test/templates/format-test.yaml, test/templates/null.yaml
=> Bugfixes for 1.3 release

cft/format/format.go, cft/format/format_test.go, cft/parse/parse.go, test/templates/fmtfindinmap.yaml, test/templates/fmtziplines.yaml, test/templates/fmtziplinesfolded.yaml, test/templates/fmtziplinesok.yaml
=> Fix formatting issue with multiline strings

cft/format/format_test.go, cft/format/json.go
=> Fix fmt error with FindInMap for JSON

cft/pkg/module.go, docs/README.tmpl, test/modules/bucket.yaml, test/modules/expect.yaml, test/templates/ext-ref-module.yaml, test/templates/module.yaml
Another bug fix for Refs in modules.
=> Module refs

cft/pkg/module.go, cft/pkg/util.go, test/modules/bucket.yaml, test/modules/expect.yaml, test/templates/module.yaml
A few bugfixes related to a hook project in the community registry extensions repo.
=> Fix module for hook

internal/aws/console/console.go
Haven't tested this yet, waiting to get access to govcloud.
=> Different URIs for GovCloud

pkl/cloudformation.pkl, pkl/patterns/README.md, pkl/patterns/bucket.pkl, pkl/patterns/function.pkl, pkl/patterns/role.pkl, pkl/patterns/vpc.pkl, scripts/pkl-patterns.sh, scripts/pklgen.sh, test/pkl/bucket.pkl, test/pkl/lambda.pkl, test/pkl/module-output.pkl, test/pkl/role.pkl, test/pkl/use-module-output.pkl, test/pkl/vpc-pattern.pkl
A new pattern, and changes to the others to make the consistent.
=> Pkl lambda

go.mod, go.sum, internal/aws/cfn/cfn.go, internal/cmd/ls/changeset.go, internal/cmd/ls/ls.go, test/templates/prop-change.yaml, test/templates/prop-change2.yaml
=> Added property level changeset support to the ls command

internal/aws/s3/s3.go, internal/table/table.go, test/templates/build/ecs/cluster.yaml
=> Stop putting ACLs on buckets and objects

cft/graph/util.go, internal/cmd/tree/tree_test.go, test/templates/fix-320.yaml
=> Fix tree so it correctly parses Subs

internal/dc/dc.go
=> Accept lower case parameters and tags in config file to support Git sync format

cft/pkg/directives.go, cft/pkg/module.go, cft/pkg/pkg.go
=> Fix module https download of submodules

internal/aws/ec2/ec2.go, internal/cmd/forecast/ec2_instance.go, internal/cmd/forecast/forecast.go, test/templates/forecast/ec2-eucentral-fail.yaml
=> Fixed paging bug with instance type check

cft/format/pkl.go, scripts/integ.sh, test/pkl/PklProject, test/pkl/PklProject.deps.json, test/pkl/condition-stringlike.pkl, test/templates/condition-stringlike.json, test/templates/condition-stringlike.yaml
https://github.com/aws-cloudformation/cloudformation-pkl/discussions/12
=> Fixed Pkl generation for maps with special characters in the name

internal/aws/cfn/cfn.go, internal/cmd/deploy/deploy.go
=> Add option to name a change set on creation

internal/cmd/deploy/deploy.go, scripts/integ.sh
=> Fixed bug with named stack and change set

go.mod, go.sum, internal/aws/sagemaker/sagemaker.go, internal/cmd/forecast/README.md, internal/cmd/forecast/forecast.go, internal/cmd/forecast/sagemaker-notebook-instance-codes.json, internal/cmd/forecast/sagemaker.go, test/templates/forecast/sagemaker-notebook.yaml
- SageMaker notebook instance quotas
=> Add forecast check for SageMaker limits

internal/aws/s3/s3.go, internal/cmd/forecast/README.md, internal/cmd/forecast/forecast.go, internal/cmd/forecast/forecast_integ.sh, internal/cmd/forecast/lambda.go, test/templates/forecast/lambda-fail.yaml, test/templates/forecast/lambda-succeed.yaml
=> Forecast issues with lambda functions

internal/cmd/merge/merge.go, test/templates/merge1.yaml, test/templates/merge2.yaml
=> Add node-style to merge

cft/format/pkl.go, internal/cmd/merge/merge.go, internal/cmd/merge/merge_test.go, internal/cmd/merge/outputs.go, internal/cmd/merge/util.go, scripts/integ.sh, test/pkl/condition-stringlike.pkl, test/templates/merge-out-1.yaml, test/templates/merge-out-2.yaml
=> When merging templates with Outputs, replace Imports that reference Exported Names

internal/aws/s3/s3.go, internal/cmd/rain/rain.go
=> Allow overriding the expected bucket owner

internal/cmd/rain/rain.go
=> Add s3 bucket params to stackset command

cft/graph/util.go, cft/parse/parse_sub.go, cft/parse/parse_sub_test.go, cft/pkg/constants.go, cft/pkg/constants_test.go, cft/pkg/module.go, cft/pkg/pkg.go, internal/cmd/cc/resolve.go, test/templates/constants.yaml
=> Fix bugs in Constants and Sub processing

cft/cft.go, cft/pkg/module.go, cft/pkg/module_test.go, cft/pkg/pkg.go, internal/cmd/deploy/deploy.go, internal/cmd/pkg/pkg.go, test/templates/analytics.yaml
=> Add analytics to template Metadata

internal/cmd/merge/merge.go, internal/cmd/merge/merge_test.go, internal/cmd/merge/outputs.go, internal/cmd/merge/util.go
=> Fix breaking change to merge

cft/pkg/module.go, cft/pkg/pkg.go, internal/node/node.go, internal/node/node_test.go, test/templates/analytics2.yaml, test/templates/analytics3.yaml
=> Fixing duplicate analytics node
