aws-cloudformation/rain

- console/console.go
This change allows either "y" or "Y" to be acceptable as a "yes" response
for confirmation prompts, whereas the previous behaviour was to only
accept "Y".
For example, when performing a `rain deploy`, the current behaviour is:
```
Do you wish to continue? (Y/n) y
User cancelled deployment.
< rain exits >
```
With this change:
```
Do you wish to continue? (Y/n) y
< deployment proceeds >
```
> Accept lower-case 'y' responses to confirmation prompt

- cfn/parse/parse_test.go
- cfn/parse/test.yaml
- cfn/parse/transform.go
When parsing templates with timestamp versions `rain` would fail.
This at the top of a template would break it.
```
"AWSTemplateFormatVersion": 2010-09-09
```
So to mitigate this I am using the transform to ensure all timestamps are converted to strings.
I have added testes to illustrate the problem, these fail without the change.
> Fix for bare timestamps in yaml being converted to dates

- cfn/cfn.go
- cfn/format/encoder.go
- cfn/format/format.go
- client/cfn/cfn.go
- cmd/fmt.go
- cmd/fmt_test.go
*Issue #, if available:* #39 
*Description of changes:* Do not force formatting of template on deploy. This avoids the reference check. In addition, do not panic on reference check failure. Added option to format without sorting to `fmt` command.
> Fix reference check

- internal/cmd/deploy/util.go
*Issue #52, if available:* 
* fix #52
Added explicitly file closing for deleting correctly on Windows environment.
> Explicitly close temp template file before deleting it

- internal/cmd/deploy/deploy.go
No Issue #, related #52 .
In current latest master branch, `rain deploy` treats incorrectly default stack name on Windows. 
[path](https://golang.org/pkg/path/) Package doesn't treat backslash as a separator, so if <template> parameter is specified as absolute path, default stack name is as follows.
```powershell
PS > $env:AWS_PROFILE="my_profile"
PS > .\rain.exe deploy C:\temp\sample.yaml
Preparing template 'C:\temp\sample.yaml' ˙ ·
Loading AWS config ˙ ·
Checking current status of stack 'C-temp-sample' .·
Creating change set  .˙
CloudFormation will make the following changes:
Stack C-temp-sample:
+ AWS::S3::Bucket MyBucket
Do you wish to continue? (Y/n) 
```
This pull request improves this behavior as expected.
```powershell
PS > …
```
> Corrects the default stack name of rain deploy on Windows

- go.mod
- go.sum
- internal/console/console.go
- internal/console/console_windows.go
* No Issue # 
This pull request mainly improves terminal detection on Windows.  
Since Windows 10 ver.1607, ANSI escape code supported on Windows and `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag is used for detecting and enabling this feature.
* See : [Console Virtual Terminal Sequences](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences?redirectedfrom=MSDN)
In addition, I have modified it to use the [term](https://pkg.go.dev/golang.org/x/term) package for unified processing.
> Improve terminal detection logic.

- internal/cmd/deploy/deploy.go
- internal/cmd/deploy/deploy_test.go
*Issue #11 
*Description of changes:* Adds support for  parameters/tags as a json file for the deploy command. See the issue for more details on why this may be useful.
> Add cli config flag

- internal/aws/cfn/cfn.go
- internal/aws/cfn/mock.go
- internal/cmd/deploy/deploy.go
- internal/cmd/deploy/deploy_test.go
*Issue #, if available:* #71
*Description of changes:* Add `--role-arn` option for deploy sub command to set service role.
> Add --role-arn option for deploy sub command.

- internal/aws/cfn/cfn.go
- internal/cmd/deploy/deploy.go
*Issue #, if available:* #73
*Description of changes:* When change set includes no change, rain exits with a success code instead of a panic.
> fix: exit with a success code instead of a panic when change set includes no change.

- cft/parse/parse.go
- cft/parse/transform.go
An incorrect `!GetAtt` reference only for _logicalName_ (e.g. `!GetAtt Resource1`) caused an out-of-array reference
```
$ ./rain fmt test.yaml --debug
panic: runtime error: index out of range [1] with length 1 [recovered]
panic: runtime error: index out of range [1] with length 1
goroutine 1 [running]:
github.com/aws-cloudformation/rain/internal/cmd.execute.func1(0xc000587f58)
github.com/aws-cloudformation/rain/internal/cmd/wrap.go:77 +0x225
panic(0x1943d00, 0xc0000c0450)
runtime/panic.go:965 +0x1b9
github.com/aws-cloudformation/rain/cft/parse.parseGetAtt(0xc000610be0)
github.com/aws-cloudformation/rain/cft/parse/transform.go:33 +0x2cf
github.com/aws-cloudformation/rain/cft/parse.TransformNode(0xc000610b40) …
```
> Fix return an error of index out of range without panic

- docs/rain_rm.md
- internal/aws/cfn/cfn.go
- internal/aws/cfn/mock.go
- internal/cmd/deploy/deploy.go
- internal/cmd/deploy/util.go
- internal/cmd/rm/rm.go
- internal/cmd/rm/rm_test.go
*Issue #, if available:* -
*Description of changes:* Add --role-arn option for remove sub command.
The PR https://github.com/aws-cloudformation/rain/pull/81 added this flag to the deploy command. On occasion we needed this flag for the remove (delete) command too.
> Add --role-arn option for remove sub command.

- cft/build/build.go
- internal/cmd/build/build_test.go
*Description of changes:* rain build will now omit the `Properties` field if it's empty. example:
before:
`rain build AWS::S3::Bucket -b`
```
AWSTemplateFormatVersion: "2010-09-09"
Description: Template generated by rain
Resources:
MyBucket:
Type: AWS::S3::Bucket
Properties: {}
```
now:
`rain build AWS::S3::Bucket -b`
```
AWSTemplateFormatVersion: "2010-09-09"
Description: Template generated by rain
Resources:
MyBucket:
Type: AWS::S3::Bucket
```
> build now omits the properties field in template if properties is empty

- internal/aws/aws.go
- internal/aws/console/console.go
- internal/cmd/console/util.go
- internal/config/version.go
Fixes #108. Removing `SessionDuration` from the call to get the session token if we get a 400 error from the endpoint.
> Removed SessionDuration to fix console bug

- internal/aws/s3/mock.go
- internal/aws/s3/s3.go
- internal/cmd/merge/merge.go
- internal/cmd/rain/rain.go
- Added optional `--s3-bucket` flag to `pkg` command. Would be used to specify an already created s3 bucket with a custom name.
- Added optional `--s3-prefix` flag to `pkg` command. Would be used to put assets into 'subfolders' within the s3 bucket.
- Added optional `--output` flag to `merge` command.
Mimicking `aws cloudformation package` command by adding `--s3-bucket` and `--s3-prefix` flags.
Not sure if these flags should be added to other commands but I added them to `rain pkg` and `rain deploy`.
> Added helpful flags to pkg & merge commands

- cft/pkg/pkg.go
- cft/pkg/pkg_test.go
- cft/pkg/rain.go
- cft/pkg/util.go
- cft/tags.go
- docs/rain_pkg.md
- internal/aws/s3/mock.go
- internal/aws/s3/s3_test.go
- internal/cmd/pkg/pkg.go
I find it very useful to inject environmental variables into the template. Some use cases would include injecting a default AMI name into a template based on what environment the template is being packaged for (staging/production). For me this happens during CI/CD.
The name of the environmental variable is passed as the only argument to `Rain::Env`.
If the environmental variable does not exist, then an error is returned, otherwise the value of the environmental variable is injected into the template as a string.
Given a file named `template.yaml` with the following contents:
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: Template generated by rain
Parameters:
ImageId:
Type: String
Default: !Rain::Env AMI_IMAGE
Resources:
MyInstance:
Type: AWS::EC2::Instance
Properties: …
```
> Implemented Rain::Env for pkg command

- internal/cmd/deploy/util.go
https://github.com/aws-cloudformation/rain/issues/152
Print `no changes in resources` only when no changes in the resource of the nested stack
> fix: panic when no changes in the resources of the nested ChangeSet

- internal/aws/cfn/cfn.go
- internal/aws/cfn/mock.go
- internal/cmd/deploy/deploy.go
- test/func_test.go
- test/templates/emptychangeset.template
*Description of changes: Bug fixes for stack and stack-set deployment*
- *Bug 1*(Line 101 of internal/cmd/deploy/deploy.go) : deploying a stack with no changes causes an the cli to throw an error with the message "No updates are to be performed."; fixed it by added new messages and overhauling the checking method
- *Bug 2*(Line 515 of internal/aws/cfn/cfn.go) : error handling in the cfn module, causes the cli to panic if there is an error in the stackset template; fixed it by handling it correctly.
> fix: bugs in stack and stacksets deployment

- cft/format/format.go
- cft/format/format_test.go
*Issue #161
Cannot close multi-line values when startMultilineIndent is 0.
https://github.com/aws-cloudformation/rain/blob/2d9825b646ff73e0725f109aec787faebc880069/cft/format/format.go#L66
```
$ rain fmt template.yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: |
Test template
Parameters:
ApiNames:
Type: String
Resources:
DashboardTest:
Type: AWS::CloudWatch::Dashboard
Properties:
DashboardName: Test
DashboardBody: Test
```
Close multi-line values even if it returns to the same indent
- add: unit-test for multi-line value
- fix: terminate multi-line values even if it returns to the same indent
before
```
$ go test ./cft/format/
--- FAIL: TestFormatDefault (0.01s)
format_test.go:395:   strings.Join({
"Description: |\n  An example template for testing rain …
```
> fix: close multi-line values even if it returns to the same indent

- .github/workflows/test.yml
- cft/pkg/module.go
- cft/pkg/pkg.go
- cft/pkg/rain.go
- cft/pkg/tmpl/s3-in-module-module.yaml
- cft/pkg/tmpl/s3-in-module-template.yaml
- internal/config/version.go
- internal/node/node.go
I had to resolve a reference to the property set by the parent template, since the S3 directive handler expects the Path to be an actual string. Fixes #180
> Fix S3 in Modules

- cft/format/format.go
- cft/format/format_test.go
*Issue #110, if available:*
Sometimes YAML package generates multiline strings with chomping (e.g. |2+), but the rain format post-processing seems to ignore this.
Change from an exact match of `|` or `>` to a regex match that complies with YAML spec.
> fix: support literal with chomping indicator

- internal/cmd/fmt/fmt.go
*Issue #196, if available:*
When rain fmt `parse.Verify` fails, show formatted output with --debug
> add: show formatted output with debugging

- .github/workflows/build.sh
- internal/config/version.go
*Issue #, if available:*  aws-cloudformation/rain#151 and aws-cloudformation/rain#201
*Description of changes:* Changes release artifact naming for Mac to align with Go naming with the use of `darwin` instead of `macos`.  Additionally, adds building `darwin/arm64` for Apple silicon.
> ci: Align release artifacts with Go naming for Mac

- internal/cmd/stackset/stackset_deploy.go
*Issue #, if available:* N/A
This merge-request add support for AWS organization: one can specify an organization root ID or organizational unit IDs instead of a list of account IDs
The configuration looks like this:
```yaml
---
StackSet:
autodeployment:
enabled: true
retainstacksonaccountremoval: false
managedexecution:
active: true
permissionmodel: SERVICE_MANAGED
StackSetInstanses:
operationpreferences:
regionconcurrencytype: PARALLEL
maxconcurrentpercentage: 100
failuretolerancepercentage: 80
regions:
- ap-northeast-1
- ap-northeast-2
- ap-northeast-3
- ap-south-1
- ap-southeast-1
- ap-southeast-2
- ca-central-1
- eu-central-1
- eu-north-1
- eu-west-1
- eu-west-2
- eu-west-3
- sa-east-1
- us-east-1
- us-east-2
- us-west-1
- us-west-2
deploymenttargets: …
```
> feat: Allow deploying stack-set to organizational units

- internal/aws/iam/iam.go
- internal/aws/iam/iam_test.go
Changed the ARN returned by GetCallerIdentity to return the IAM Role ARN if it is of the "assume-role" style, otherwise the ARN is returned as is.
#216 
**IAM user**
```sh
$ aws sts get-caller-identity
{
"UserId": "xxxxxxxxxxxxxxxxxxxxx",
"Account": "xxxxxxxxxxxx",
"Arn": "arn:aws:iam::xxxxxxxxxxxx:user/khrmoryz"
}
$ go run cmd/rain/main.go forecast --experimental ./test/templates/success.template s3 --params BucketName=foo
Clear skies! 🌞 All 3 checks passed.
```
**Assume-Role**
```sh
$ aws sts get-caller-identity
{
"UserId": "xxxxxxxxxxxxxxxxxxxxx:botocore-session-1701516435",
"Account": "xxxxxxxxxxxx",
"Arn": "arn:aws:sts::xxxxxxxxxxxx:assumed-role/Admin/botocore-session-1701516435"
}
$ go run cmd/rain/main.go forecast --experimental ./test/templates/success.template s3 --params …
```
> fix: support IAM user identity in GetCallerArn

- internal/aws/s3/s3.go
> Adding a sleep to resolve race condition

- internal/aws/cfn/cfn.go
*Issue #213 :*
- Handle S3 url for S3 in AWS Mainland China in case of template upload.
*Tests:*
- Tests are made in our CI/CD environment in Beijing region :
```
DEBUG: Preparing template 'main.yml'
DEBUG: Loading AWS config
DEBUG: Artifact bucket: cf-templates-m89vz00plzen-cn-north-1
DEBUG: transform path: Resources/*|Type==AWS::CloudFormation::Stack/Properties/TemplateURL
DEBUG: transform path: Resources/*|Type==AWS::CloudFormation::Stack/Properties/TemplateURL
DEBUG: transform path: Resources/*|Type==AWS::CloudFormation::Stack/Properties/TemplateURL
DEBUG: transform path: Resources/*|Type==AWS::CloudFormation::Stack/Properties/TemplateURL
DEBUG: transform path: Resources/*|Type==AWS::CloudFormation::Stack/Properties/TemplateURL
DEBUG: transform path: …
```
> Fix: update S3 url for handling china region

- internal/aws/bedrock/bedrock.go
*Issue https://github.com/aws-cloudformation/rain/issues/235, if available:*
In attempting to correct this, 
I assume this part 
https://github.com/aws-cloudformation/rain/blob/10c3391e327fd62504b9cd954a5a33428a0f5fb5/internal/aws/bedrock/bedrock.go#L30-L33
could be modified by specifying `:1` at the end of `claudeV2ModelID` as follows
```
const (
claudePromptFormat = "\n\nHuman:%s\n\nAssistant:"
claudeV2ModelID    = "anthropic.claude-v2:1"
)
```
When I tried the modified one, it actually worked like this
```
$ ./rain build -p "VPC with 1 private and 1 public subnet"
AWSTemplateFormatVersion: '2010-09-09'
Description: VPC with 1 public and 1 private subnet
Resources:
VPC:
Type: AWS::EC2::VPC
Properties:
CidrBlock: 10.0.0.0/16
EnableDnsSupport: true …
```
> Fix:update specification of claude v2 modelid

- cft/format/format_test.go
- cft/format/transform.go
- test/templates/fmttestinput.yaml
- test/templates/roundtrip.yaml
When formatting to JSON and back to YAML, JSON styles were left in the YAML nodes, which caused inconsistent formatting.
This *might* be considered a breaking change, because one of the effects is to now format `!Sub` without double quotes, even if they were in the original.
Fixes #170
> Fix formatting round trip - Style is always 0

- cft/pkg/anchor_test.go
- cft/pkg/pkg.go
- cft/pkg/tmpl/anchors-expect.yaml
- cft/pkg/tmpl/anchors.yaml
Fixes #257 
Instead of using just the `fmt` command, first `pkg` and then pipe into `fmt`.
Going to leave this a draft for now. All tests are passing but there are some templates with anchors that will cause `fmt` to fail, which means you would have to package first. That may be unexpected for some users, although the anchors would fail when you send them to CloudFormation, so maybe it doesn't matter. The issue is due to default sorting, which puts the anchors out of order and the go yaml parser can't resolve them. Maybe that's ok? If you want to format a template with anchors you can add `--unsorted` and it will work.
@hariprakash-j, @khmoryz, @null93, @iainelder 
@j5nb4l
> Fixed template packaging to resolve anchors

- cft/cft.go
- cft/diff/compare.go
- cft/parse/parse.go
- cft/pkg/pkg.go
- go.mod
- go.sum
- internal/aws/ccapi/ccapi.go
- internal/aws/cfn/cfn.go
- internal/aws/cfn/mock.go
- internal/cmd/cc/README.md
- internal/cmd/cc/cc.go
- internal/cmd/cc/deploy.go
- internal/cmd/cc/deployment.go
- internal/cmd/cc/drift.go
- internal/cmd/cc/rm.go
- internal/cmd/cc/state.go
- internal/console/colours.go
- internal/console/console.go
This only applies to templates deployed with `rain cc deploy`, an experimental feature that bypasses CloudFormation stacks and deploys resources directly with Cloud Control API. We might also consider building something like this for normal CloudFormation deployments.
As sample of the UI for detecting drift in a resource:
@hariprakash-j, @khmoryz, @null93, @iainelder, would love some feedback on this. (Still working on approvals so I can add you as actual reviewers)
> Added a `cc drift` command that detects and remediates drift

- cft/diff/compare.go
- cft/format/format.go
- cft/format/format_test.go
- cft/format/transform.go
- test/templates/getazs-null.yaml
> Fix format bug with empty string and null

- cft/pkg/pkg.go
- cft/pkg/tmpl/anchors-expect.yaml
- cft/visitor/visitor.go
Fixes aws-cloudformation/rain#362
> Package Command Should Preserve Map Key Order

- docs/rain_build.md
- internal/cmd/build/build.go
- internal/cmd/build/interactive.go
ref: https://github.com/aws-cloudformation/rain/issues/368
model-id's below.
https://aws.amazon.com/jp/blogs/aws/anthropics-claude-3-opus-model-on-amazon-bedrock/
> Add support for Claude3-Opus

- internal/cmd/logs/logs.go
- internal/cmd/logs/logs_test.go
- internal/cmd/logs/util.go
#236
Add -s / --since-user-initiated flag for only showing logs since the last 'User Initiated' event
> Implement a "User Initiated" filter option for the rain logs command

- docs/rain_build.md
- internal/cmd/build/build.go
- internal/cmd/build/interactive.go
ref: https://github.com/aws-cloudformation/rain/issues/437
model-id's below.
https://aws.amazon.com/jp/blogs/news/anthropics-claude-3-5-sonnet-model-now-available-in-amazon-bedrock-the-most-intelligent-claude-model-yet/
The original issue also mentioned Llama3.1. Please let me know if this needs to be addressed in this PR.
---
> Add support for Claude3.5-Sonnet

- .github/workflows/build.sh
*Issue #515*
Simply adds support for cross compiling for linux/arm64
> Adds Cross Compilation support for Linux ARM 64

- internal/aws/cfn/cfn.go
*Issue #538 
*Description of changes: Switch to using regional S3 endpoints (rather than the legacy global endpoint) when uploading large templates to S3 prior to deployment. This should better support US Gov regions, as well as any commercial region created after March 20, 2019 (per https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#VirtualHostingBackwardsCompatibility)
The change was successfully tested locally in us-east-1 and us-gov-west-1
> Use regional endpoints for large template uploads to S3

- internal/aws/cfn/cfn.go
- internal/cmd/deploy/deploy.go
Fixes #526. Add `--nested-change-set=false` to the `deploy` command.
> Make including nested stacks in a change set optional

- internal/cmd/rain/rain.go
- internal/cmd/stackset/stackset.go
*Issue #, if available:* #528
While using the feature requested in the mentioned ticket, rain didn't accept the `--s3-bucket` on `rain stackset deploy`. It only worked for `rain stackset` the subcommand 'root'. 
After investigating the original change and comparing how the s3 commands are made available in `rain cc`, `rain deploy` and `rm` I offer this MR that allows the use of the s3-commands with `rain stackset deploy`. 
> Fix s3bucket option for stackset deploy

- internal/aws/cfn/patch.go
- internal/aws/cfn/schema.go
AWS::EC2::LaunchTemplate has a property that's not defined
> Fixing incorrect schema

- internal/cmd/stackset/stackset_deploy.go
*Issue #, if available:* None
Documentation change:
- Put the example YAML mentioned in `rain stackset deploy` in a Markdown code block, so new lines and syntax is preserved after generating into Markdown. 
- Add link to the example configuration file located in the test/samples folder.
Adding the code block syntax affects the help message on the CLI slightly. However, I do understand if the link is too much. Just let me know if any changes are desired.
> docs: add markdown formatting to example text and link to example file

- cft/cft.go
- cft/format/json.go
- cft/format/uncdk.go
- cft/format/uncdk_test.go
- internal/cmd/fmt/fmt.go
- test/templates/notcontains.yaml
- test/templates/uncdk-expect.yaml
- test/templates/uncdk.yaml
`rain fmt --uncdk` removes CDK Metadata and simplifies logical IDs from templates that were generated with `cdk synth`. This can be useful for pipelines where CDK is used strictly as a code generator and the templates are deployed separately, or if you use CDK as a starting point for declarative YAML CloudFormation development. 
This command only looks at a single template. The `rain merge` command can be used to stitch together separate templates from CDK output.
> Added uncdk to fmt command

- README.md
- cft/pkg/directives.go
- cft/pkg/tmpl/s3-extension-template.yaml
- cft/pkg/util.go
- docs/README.tmpl
- docs/rain_pkg.md
- internal/aws/cfn/cfn.go
- internal/aws/s3/s3.go
- scripts/integ.sh
*Issue #, if available:* #643 
Some AWS services require that the objects they access in S3 have a particular extension.
This meant rain was previously incompatbile with that requirement.
this change allows a user to specify the extension to append to the uploaded artifact in S3.
> Adds optional Extension property to set extension on uploaded artifact

- internal/cmd/deploy/deploy.go
Suppose we have a changeset that imports the resource (ex. a RDS DB instance).
```
$ ./rain ls rms-8-0-34 -c rms-8-0-34-changeset-v0
Arn: ***
Created: 2025-02-24 15:26:03.717 +0000 UTC
Description:
Status: AVAILABLE/CREATE_COMPLETE (Verify that resources and their properties defined in the template match the intended configuration of the resource import to avoid unexpected changes.)
Parameters: (None)
Changes:
Import [Replace]: RDSforMySQL (AWS::RDS::DBInstance) rms-8-0-40-created-by-cfn
```
When we try to execute a changeset using the `rain deploy` command, we get the following **failed deploying stack** message.
```
$ rain deploy --changeset rms-8-0-34 rms-8-0-34-changeset-v0
Executing changeset 'rms-8-0-34-changeset-v0' as stack 'rms-8-0-34' in ap-northeast-1.
Stack rms-8-0-34: …
```
> fix: Update messages when deploying a changeset when importing resources

- cft/format/format_test.go
- cft/format/transform.go
#653
Ensure ambiguous YAML scalars (`ON`, `OFF`, `YES`, `NO`, `TRUE`, `FALSE`) remain quoted to prevent unintended type conversion in CloudFormation templates. Includes tests to verify correct handling in `Parameters` and `Properties`.
> Fix #653: incorrectly strips quotes from string values that resemble YAML booleans

- cft/format/format_test.go
- cft/format/transform.go
**PR Description**  
This PR introduces a new node style, **`strict-booleans`**, which aligns Rain with YAML 1.2 by treating only `true` and `false` as booleans. Values like `yes`, `no`, `on`, and `off` become strings instead of being ambiguously parsed. While this change is currently placed behind a new style flag, it may be preferable to make it the default behavior in future releases to avoid CloudFormation type mismatches and better adhere to the YAML 1.2 specification.
> Add strict-booleans node style

- .pre-commit-hooks.yaml
**Issue #, if available:**
#671
**Description of changes:**
This PR updates the `.pre-commit-hooks.yaml` file to replace the outdated `cfn-format` hook with two new hooks using the `rain` CLI tool:
- `rain-format`: Formats AWS CloudFormation templates using `rain fmt -w`
- `rain-verify`: Verifies formatting without modifying files using `rain fmt -v`
These hooks support both YAML and JSON CloudFormation templates (`.yaml`, `.yml`, and `.json` file extensions).
Using `rain` in pre-commit hooks provides a modern and maintained way to enforce consistent formatting in CloudFormation templates. It also enables integration with the [pre-commit framework](https://pre-commit.com/) for both local development and CI pipelines.
By submitting this pull request, I confirm that you can use, modify, …
> Update .pre-commit-hooks.yaml to use rain instead of cfn-format
